export const dynamic = 'force-dynamic';
import Link from 'next/link';
import { PublicNav, PublicFooter } from '@/components/layout/PublicNav';
import { HelpCircle, Search, MessageCircle, BookOpen, Zap, Globe, CreditCard, ArrowRight } from 'lucide-react';

const categories = [
  { icon: Zap,          color: 'blue',   title: 'Getting Started',
    articles: ['How do I create my first article?', 'How to connect a WordPress site', 'What are AI credits?', 'Choosing the right AI model'] },
  { icon: Globe,        color: 'purple', title: 'WordPress',
    articles: ['Why is my WordPress connection failing?', 'How to get an Application Password', 'Publishing fails — what to check', 'Managing multiple sites'] },
  { icon: CreditCard,   color: 'green',  title: 'Billing & Credits',
    articles: ['How are word credits counted?', 'Why were my credits deducted incorrectly?', 'How to purchase a top-up package', 'Refund policy'] },
  { icon: HelpCircle,   color: 'yellow', title: 'Account & Settings',
    articles: ['How to reset my password', 'Changing notification preferences', 'Deleting my account', 'Two-factor authentication (coming soon)'] },
];

const colorMap: Record<string, string> = {
  blue: 'bg-blue-50 text-blue-600', purple: 'bg-purple-50 text-purple-600',
  green: 'bg-green-50 text-green-600', yellow: 'bg-yellow-50 text-yellow-600',
};

const faqs = [
  { q: 'What are AI credits?',
    a: 'AI credits are word credits — each word generated by the AI consumes 1 credit. A 1,500-word article uses 1,500 credits. Credits reset monthly for subscription plans and never expire for top-up purchases.' },
  { q: 'Which AI models are available?',
    a: 'ContomatorAI supports Claude (Anthropic), GPT-4 (OpenAI), and Gemini (Google). You can select the model per article based on your preference and available credits.' },
  { q: 'How do I connect my WordPress site?',
    a: 'Go to Dashboard → WordPress Sites → Add Site. You will need your WordPress site URL, your username, and an Application Password generated from your WordPress user profile (Users → Profile → Application Passwords).' },
  { q: 'Can I cancel my subscription anytime?',
    a: 'Yes. You can cancel your subscription from the Billing page at any time. You will retain access until the end of your current billing period.' },
  { q: 'Is there a free trial?',
    a: 'Yes — new accounts receive a free trial with 5,000 words to test the platform. No credit card is required to start.' },
  { q: 'What happens when I run out of credits?',
    a: 'Content generation will be paused until you top up. You can purchase additional word credit packages from the Billing page at any time without changing your subscription.' },
];

export default function HelpPage() {
  return (
    <div className="min-h-screen bg-gradient-to-br from-blue-50 via-white to-purple-50">
      <PublicNav active="Help" />

      <section className="pt-20 pb-12 text-center">
        <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="inline-flex items-center bg-blue-50 border border-blue-200 rounded-full px-4 py-2 text-blue-700 text-sm font-medium mb-6">
            <HelpCircle className="w-4 h-4 mr-2" /> Help Center
          </div>
          <h1 className="text-4xl md:text-5xl font-bold text-gray-900 mb-6">
            How can we{' '}
            <span className="bg-gradient-to-r from-blue-600 to-purple-600 bg-clip-text text-transparent">
              help you?
            </span>
          </h1>
          <p className="text-xl text-gray-600 mb-8">
            Search our knowledge base or browse by category below.
          </p>
          <div className="max-w-xl mx-auto relative">
            <Search className="absolute left-4 top-1/2 -translate-y-1/2 w-5 h-5 text-gray-400" />
            <input
              type="text"
              placeholder="Search for answers..."
              className="w-full pl-12 pr-5 py-4 rounded-xl border border-gray-300 focus:ring-2 focus:ring-blue-500 focus:border-transparent shadow-sm text-gray-900 bg-white"
            />
          </div>
        </div>
      </section>

      {/* Categories */}
      <section className="pb-16">
        <div className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="grid grid-cols-1 md:grid-cols-2 gap-8 mb-16">
            {categories.map(({ icon: Icon, color, title, articles }) => (
              <div key={title} className="bg-white rounded-2xl border border-gray-100 shadow-sm p-8">
                <div className="flex items-center mb-5">
                  <div className={`w-10 h-10 ${colorMap[color]} rounded-xl flex items-center justify-center mr-3`}>
                    <Icon className="w-5 h-5" />
                  </div>
                  <h3 className="text-lg font-bold text-gray-900">{title}</h3>
                </div>
                <ul className="space-y-3">
                  {articles.map(a => (
                    <li key={a} className="flex items-center text-sm text-blue-600 hover:text-blue-800 cursor-pointer transition-colors">
                      <ArrowRight className="w-4 h-4 mr-2 flex-shrink-0" />{a}
                    </li>
                  ))}
                </ul>
              </div>
            ))}
          </div>

          {/* FAQ */}
          <h2 className="text-3xl font-bold text-gray-900 mb-8 text-center">Frequently Asked Questions</h2>
          <div className="space-y-4 max-w-3xl mx-auto mb-16">
            {faqs.map(({ q, a }) => (
              <div key={q} className="bg-white rounded-xl border border-gray-100 shadow-sm p-6">
                <h4 className="font-semibold text-gray-900 mb-2">{q}</h4>
                <p className="text-gray-600 text-sm leading-relaxed">{a}</p>
              </div>
            ))}
          </div>

          {/* Still stuck */}
          <div className="bg-gradient-to-r from-blue-600 to-purple-600 rounded-2xl p-8 text-white text-center">
            <MessageCircle className="w-12 h-12 mx-auto mb-4 opacity-80" />
            <h2 className="text-2xl font-bold mb-2">Still need help?</h2>
            <p className="text-blue-100 mb-6">Our support team typically responds within 2 hours.</p>
            <Link href="/contact" className="bg-white text-blue-600 px-8 py-3 rounded-lg font-semibold hover:bg-gray-50 transition-colors inline-flex items-center">
              Contact Support <ArrowRight className="ml-2 h-5 w-5" />
            </Link>
          </div>
        </div>
      </section>

      <PublicFooter />
    </div>
  );
}
