'use client';
export const dynamic = 'force-dynamic';

import { useState } from 'react';
import Link from 'next/link';
import { PublicNav, PublicFooter } from '@/components/layout/PublicNav';
import {
  HelpCircle, Search, MessageCircle, Zap, Globe, CreditCard,
  ArrowRight, ChevronDown, ChevronUp, X,
} from 'lucide-react';

const categories = [
  {
    icon: Zap, color: 'blue',
    title: 'Getting Started',
    articles: [
      {
        q: 'How do I create my first article?',
        a: 'Go to Dashboard → New Content. Choose your AI model, enter a topic or keyword, set your desired word count and tone, then click Generate. Your article will appear in your content library within seconds.',
      },
      {
        q: 'How to connect a WordPress site',
        a: 'Navigate to Dashboard → WordPress Sites → Add Site. Enter your WordPress URL, your admin username, and an Application Password. To create an Application Password, go to your WordPress dashboard under Users → Profile → Application Passwords.',
      },
      {
        q: 'What are AI credits?',
        a: 'AI credits are word credits — every word generated by the AI consumes one credit. A 1,500-word article uses 1,500 credits. Subscription plans include a monthly credit allowance that resets each billing cycle. Top-up credits never expire.',
      },
      {
        q: 'Choosing the right AI model',
        a: 'ContomatorAI supports Claude (best for nuanced, long-form writing), GPT-4 (strong general-purpose content), and Gemini (fast, cost-efficient). You can select the model on a per-article basis. All models produce SEO-optimised output.',
      },
    ],
  },
  {
    icon: Globe, color: 'purple',
    title: 'WordPress',
    articles: [
      {
        q: 'Why is my WordPress connection failing?',
        a: 'The most common cause is an incorrect Application Password. Ensure you copied it immediately after creation — WordPress only shows it once. Also check that your WordPress URL includes the correct protocol (https://) and has no trailing slash.',
      },
      {
        q: 'How to get an Application Password',
        a: 'Log into your WordPress admin. Go to Users → Profile and scroll to the Application Passwords section. Enter a name for the password (e.g. "ContomatorAI"), click Add New Application Password, and copy the generated password immediately.',
      },
      {
        q: 'Publishing fails — what to check',
        a: 'First verify your site connection is active under WordPress Sites. Check that your WordPress user has the Editor or Administrator role. Also confirm that the REST API is not blocked by a security plugin such as Wordfence or iThemes Security.',
      },
      {
        q: 'Managing multiple sites',
        a: 'You can add multiple WordPress sites under Dashboard → WordPress Sites. Each site is independently managed. When generating content, select the target site from the publish settings before scheduling or publishing.',
      },
    ],
  },
  {
    icon: CreditCard, color: 'green',
    title: 'Billing & Credits',
    articles: [
      {
        q: 'How are word credits counted?',
        a: 'One word generated equals one credit. Credits are deducted at the point of successful generation. If generation fails, no credits are deducted. You can monitor your credit usage in real time from the Dashboard.',
      },
      {
        q: 'Why were my credits deducted incorrectly?',
        a: 'Credits reflect the exact word count of the generated output, which may differ slightly from your requested count depending on the AI model. If you believe there is a genuine discrepancy, please contact support with the content ID and we will investigate.',
      },
      {
        q: 'How to purchase a top-up package',
        a: 'Go to Dashboard → Billing → Top-Ups. Select the package size that suits your needs and complete payment via Paystack. Top-up credits are added to your account immediately and never expire.',
      },
      {
        q: 'Refund policy',
        a: 'We offer refunds on unused subscription credit within 7 days of purchase. Top-up credits are non-refundable once consumed. To request a refund, contact support with your transaction reference and we will review your case.',
      },
    ],
  },
  {
    icon: HelpCircle, color: 'yellow',
    title: 'Account & Settings',
    articles: [
      {
        q: 'How to reset my password',
        a: 'Click "Forgot password" on the login page and enter your email address. You will receive a reset link within a few minutes. The link expires after one hour. If you do not receive the email, check your spam folder.',
      },
      {
        q: 'Changing notification preferences',
        a: 'Go to Dashboard → Settings → Notifications. You can toggle email notifications for article publications, credit alerts, weekly reports, and security events independently.',
      },
      {
        q: 'Deleting my account',
        a: 'Account deletion can be requested from Dashboard → Settings → Account → Delete Account. Please note that deletion is permanent and all content, credits, and settings will be removed. Alternatively, contact support if you need assistance.',
      },
      {
        q: 'Two-factor authentication (coming soon)',
        a: 'Two-factor authentication via an authenticator app is coming in a future update. We will notify all users by email when this feature becomes available.',
      },
    ],
  },
];

const colorMap: Record<string, string> = {
  blue:   'bg-blue-50 text-blue-600',
  purple: 'bg-purple-50 text-purple-600',
  green:  'bg-green-50 text-green-600',
  yellow: 'bg-yellow-50 text-yellow-600',
};

const faqs = [
  {
    q: 'What are AI credits?',
    a: 'AI credits are word credits — each word generated by the AI consumes 1 credit. A 1,500-word article uses 1,500 credits. Credits reset monthly for subscription plans and never expire for top-up purchases.',
  },
  {
    q: 'Which AI models are available?',
    a: 'ContomatorAI supports Claude (Anthropic), GPT-4 (OpenAI), and Gemini (Google). You can select the model per article based on your preference and available credits.',
  },
  {
    q: 'How do I connect my WordPress site?',
    a: 'Go to Dashboard → WordPress Sites → Add Site. You will need your WordPress site URL, your username, and an Application Password generated from your WordPress user profile.',
  },
  {
    q: 'Can I cancel my subscription anytime?',
    a: 'Yes. You can cancel your subscription from the Billing page at any time. You will retain access until the end of your current billing period.',
  },
  {
    q: 'Is there a free trial?',
    a: 'Yes — new accounts receive a free trial with 5,000 words to test the platform. No credit card is required to start.',
  },
  {
    q: 'What happens when I run out of credits?',
    a: 'Content generation will be paused until you top up. You can purchase additional word credit packages from the Billing page at any time without changing your subscription.',
  },
];

export default function HelpPage() {
  const [openArticle, setOpenArticle] = useState<string | null>(null);
  const [openFaq, setOpenFaq] = useState<number | null>(null);
  const [query, setQuery] = useState('');

  const toggleArticle = (key: string) =>
    setOpenArticle(prev => (prev === key ? null : key));

  const toggleFaq = (i: number) =>
    setOpenFaq(prev => (prev === i ? null : i));

  const q = query.toLowerCase().trim();

  const filteredCategories = categories
    .map(cat => ({
      ...cat,
      articles: cat.articles.filter(
        a => a.q.toLowerCase().includes(q) || a.a.toLowerCase().includes(q)
      ),
    }))
    .filter(cat => cat.articles.length > 0);

  const filteredFaqs = faqs.filter(
    f => f.q.toLowerCase().includes(q) || f.a.toLowerCase().includes(q)
  );

  const hasResults = filteredCategories.length > 0 || filteredFaqs.length > 0;

  return (
    <div className="min-h-screen bg-gradient-to-br from-blue-50 via-white to-purple-50">
      <PublicNav active="Help" />

      <section className="pt-20 pb-12 text-center">
        <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="inline-flex items-center bg-blue-50 border border-blue-200 rounded-full px-4 py-2 text-blue-700 text-sm font-medium mb-6">
            <HelpCircle className="w-4 h-4 mr-2" /> Help Center
          </div>
          <h1 className="text-4xl md:text-5xl font-bold text-gray-900 mb-6">
            How can we{' '}
            <span className="bg-gradient-to-r from-blue-600 to-purple-600 bg-clip-text text-transparent">
              help you?
            </span>
          </h1>
          <p className="text-xl text-gray-600 mb-8">
            Search our knowledge base or browse by category below.
          </p>
          <div className="max-w-xl mx-auto relative">
            <Search className="absolute left-4 top-1/2 -translate-y-1/2 w-5 h-5 text-gray-400" />
            <input
              type="text"
              value={query}
              onChange={e => setQuery(e.target.value)}
              placeholder="Search for answers..."
              className="w-full pl-12 pr-10 py-4 rounded-xl border border-gray-300 focus:ring-2 focus:ring-blue-500 focus:border-transparent shadow-sm text-gray-900 bg-white"
            />
            {query && (
              <button
                onClick={() => setQuery('')}
                className="absolute right-4 top-1/2 -translate-y-1/2 text-gray-400 hover:text-gray-600"
              >
                <X className="w-4 h-4" />
              </button>
            )}
          </div>
          {query && (
            <p className="mt-3 text-sm text-gray-500">
              {hasResults
                ? `Showing results for "${query}"`
                : `No results found for "${query}"`}
            </p>
          )}
        </div>
      </section>

      <section className="pb-16">
        <div className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8">

          {/* No results */}
          {query && !hasResults && (
            <div className="text-center py-16">
              <HelpCircle className="w-12 h-12 text-gray-300 mx-auto mb-4" />
              <h3 className="text-lg font-semibold text-gray-700 mb-2">No results found</h3>
              <p className="text-gray-500 mb-6">Try different keywords or contact our support team directly.</p>
              <Link
                href="/contact"
                className="inline-flex items-center bg-blue-600 text-white px-6 py-3 rounded-lg font-semibold hover:bg-blue-700 transition-colors"
              >
                Contact Support <ArrowRight className="ml-2 w-4 h-4" />
              </Link>
            </div>
          )}

          {/* Categories with accordion articles */}
          {(!query || filteredCategories.length > 0) && (
            <div className="grid grid-cols-1 md:grid-cols-2 gap-8 mb-16">
              {(query ? filteredCategories : categories).map(({ icon: Icon, color, title, articles }) => (
                <div key={title} className="bg-white rounded-2xl border border-gray-100 shadow-sm p-8">
                  <div className="flex items-center mb-5">
                    <div className={`w-10 h-10 ${colorMap[color]} rounded-xl flex items-center justify-center mr-3`}>
                      <Icon className="w-5 h-5" />
                    </div>
                    <h3 className="text-lg font-bold text-gray-900">{title}</h3>
                  </div>
                  <div className="space-y-2">
                    {articles.map(article => {
                      const key = `${title}::${article.q}`;
                      const isOpen = openArticle === key;
                      return (
                        <div key={article.q} className="border border-gray-100 rounded-lg overflow-hidden">
                          <button
                            onClick={() => toggleArticle(key)}
                            className="w-full flex items-center justify-between px-4 py-3 text-left hover:bg-gray-50 transition-colors"
                          >
                            <span className="text-sm font-medium text-gray-800 pr-4">{article.q}</span>
                            {isOpen
                              ? <ChevronUp className="w-4 h-4 text-gray-400 flex-shrink-0" />
                              : <ChevronDown className="w-4 h-4 text-gray-400 flex-shrink-0" />}
                          </button>
                          {isOpen && (
                            <div className="px-4 pb-4 text-sm text-gray-600 leading-relaxed border-t border-gray-100 pt-3 bg-gray-50">
                              {article.a}
                            </div>
                          )}
                        </div>
                      );
                    })}
                  </div>
                </div>
              ))}
            </div>
          )}

          {/* FAQ */}
          {(!query || filteredFaqs.length > 0) && (
            <>
              <h2 className="text-3xl font-bold text-gray-900 mb-8 text-center">
                Frequently Asked Questions
              </h2>
              <div className="space-y-3 max-w-3xl mx-auto mb-16">
                {(query ? filteredFaqs : faqs).map(({ q: question, a: answer }, i) => (
                  <div key={i} className="bg-white rounded-xl border border-gray-100 shadow-sm overflow-hidden">
                    <button
                      onClick={() => toggleFaq(i)}
                      className="w-full flex items-center justify-between px-6 py-5 text-left hover:bg-gray-50 transition-colors"
                    >
                      <span className="font-semibold text-gray-900 pr-4">{question}</span>
                      {openFaq === i
                        ? <ChevronUp className="w-5 h-5 text-gray-400 flex-shrink-0" />
                        : <ChevronDown className="w-5 h-5 text-gray-400 flex-shrink-0" />}
                    </button>
                    {openFaq === i && (
                      <div className="px-6 pb-5 text-gray-600 text-sm leading-relaxed border-t border-gray-100 pt-4 bg-gray-50">
                        {answer}
                      </div>
                    )}
                  </div>
                ))}
              </div>
            </>
          )}

          {/* Still stuck */}
          <div className="bg-gradient-to-r from-blue-600 to-purple-600 rounded-2xl p-8 text-white text-center">
            <MessageCircle className="w-12 h-12 mx-auto mb-4 opacity-80" />
            <h2 className="text-2xl font-bold mb-2">Still need help?</h2>
            <p className="text-blue-100 mb-6">Our support team typically responds within 2 hours.</p>
            <Link
              href="/contact"
              className="bg-white text-blue-600 px-8 py-3 rounded-lg font-semibold hover:bg-gray-50 transition-colors inline-flex items-center"
            >
              Contact Support <ArrowRight className="ml-2 h-5 w-5" />
            </Link>
          </div>
        </div>
      </section>

      <PublicFooter />
    </div>
  );
}
